[project]
name = "cot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-community>=0.3.13",
    "langchain>=0.3.13",
    "ollama>=0.4.4",
    "langchain-ollama>=0.2.2",
]
